### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by amandayeyan** [zhouhuan-hust/LFD_RoadSeg#1]
Hi Zhou Huan, thanks for sharing your great work on github. Could you please share the pretrained model?

**Comment by zhouhuan-hust** [comment]
Thank you for your kind words! I'm glad you found my work on GitHub useful. Regarding the pretrained model, could you please specify which model you're interested in, and I'll provide you with the necessary information or files?

**Comment by amandayeyan** [comment]
Hi, Sorry for the late reply. I'm interested in the lightweight road segmentation model.

**Comment by zhouhuan-hust** [comment]
Since the code has been refactored, the .pth file I trained before cannot match. You can train according to the readme to get the model parameters.
