### ISSUE TITLE
Questions about Constructing kittival Datasets and Modifying Parameters in Cross-Validation

### ISSUE THREAD

**Issue by 6t1pom** [zhouhuan-hust/LFD_RoadSeg#4]
Hello. Thank you for sharing your work. It is a very advanced method and I am interested in your work. 

I was trying to run the code and have two questions about cross-validation. I am a beginner, so I apologize for being off the mark with my question.

•Do I need to make the kittival dataset by myself? Or does your program include a step to divide the training data of kitti into 5 parts? I understand how you divide the images from [another closed issue](https://github.com/zhouhuan-hust/LFD_RoadSeg/issues/2). However, I would like to know whether this step is included in the program.

•I managed to get the results, but I don't seem to have been able to modify the parameters properly in the validation step. 
What I did:
Step1.  Set the training state as True and the dataset_name to "kittival", and the data_path to /xxx/data/kittival/exp1. Run LFDRoadseg_main.py.
Step2. Change the training state to False. Set the validating state as True and the dataset_name to "kittival", and the data_path to /xxx/data/kittival/exp1. Run LFDRoadseg_main.py.
Step3. Repeat step1 and step2 for exp2 to 5.
Step4. Change the validating state to False. Set the testing state as True and set the dataset_name to "kitti", and the data_path to /xxx/data/kitti. Run LFDRoadseg_main.py.
If there is a wrong process,  could you please tell me?

I apologize for asking many questions, and I would greatly appreciate your answers. Again, thank you for sharing your great work.

**Comment by zhouhuan-hust** [comment]
Question 1: Yes, you need to make the kittival dataset yourself. The program does not give the dataset generation code, and you can refer to my steps.
Question 2: For 5-fold cross-validation experiments, your steps 1-3 are correct.  If you want to generate kitti website test images, proceed to Step 4. In addition, remember to modify ckpt_path and vis_path in the outputs of the configs file.
If you have any other questions, please feel free to ask me.

**Comment by 6t1pom** [comment]
I am sorry for my late response. 
There are no further questions at this time.
Thank you for your support.

**Comment by sdutwjy** [comment]
I have a question here.

How ckpt_path and vis_path are set in the outputs of your configs file as you repeat steps 1-3. Because when I have finished validating an exp1, I go on to complete exp2 training and validating. I found that this error occurs when validating.
![屏幕截图 2024-06-25 211706](https://github.com/zhouhuan-hust/LFD_RoadSeg/assets/131098788/035e917c-e21b-40e9-b6bd-3efcec88bb58)
